### ISSUE TITLE
Todo List for SLW Mod Loader 6.0

### ISSUE THREAD

**Issue by slashiee** [Radfordhound/SLW-Mod-Loader#14]
- [x] Add detection for Sonic Generations
- [ ] Make it so checked mods get saved in the order that they're placed in
- [ ] Make piracy string
- [ ] Detect cdx files
- [ ] Find specific characters in steam_api.ini
- [ ] Compare dll files

Sonic Generations & More:
I believe that we should add support for other Sonic games in the 6.0, starting with Sonic Generations. This might get more users to use SLW Mod Loader than there is now.

Piracy:
1- Make mod loader look for these characters in steam_api.ini:

Ü, Û, °, ß, ², ±, м, л, and п.

2- Make mod loader look for files with the file type of cdx

3- What Skyth told me on discord, we can also make the mod loader compare the cracked .dll with the Steam .dll, which would pretty much prevent all cracked versions from running the mod loader.

and if it detects any of those, booting the mod loader will make a dialog box pop up saying that it has detected that you're using a pirated version. Pressing OK will close the mod loader.
